FORMAT: 1A
HOST: http://data.iotsdk.com

# Datasync API

## Classes [/1/classes/{className}]

+ Parameters
    + className (required, string, `Game`)

### Creating Objects [POST]

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: {appid}
            X-XPG-REST-API-Key: {appkey}
            Content-Type: application/json

    + Body

            {}

+ Response 201 (application/json)

    + Body
    
            {
              "createdAt": "2011-08-20T02:06:57.931Z",
              "objectId": "Ed1nuqPvcm"
            }